### ISSUE TITLE
[BUG] Version code is not optional

### ISSUE THREAD

**Issue by danielgomezrico** [tianhaoz95/fastlane-plugin-flutter_version#56]
I have the version like:
```YAML
version: 1.2
```

But it fails saying:
```bash
[07:45:58]: The full version is: 0.3.2
[07:45:58]: Verson code indicator (+) not found in pubspec.yml
```

**Comment by dhrn** [comment]
facing the same problem. any workaround?

**Comment by danielgomezrico** [comment]
I got the value by myself with this:

```ruby
require "yaml"
pubspec = YAML.load_file("#{root_path}/pubspec.yaml")

version = pubspec["version"]
```

**Comment by tianhaoz95** [comment]
ah correct, the build number was not made optional mainly because Google Play Store relies on this value to publish apps. 

However, given a second though, if what you are building is non-android or a package, it makes sense to omit the build number.

I think there should be an option that allows user to omit parts of the version. Something like:

```
flutter_version(ignore_build_number: true)["version_code"]
```

I will have some time to add that this afternoon.

If you have some time to spare, I will really appreciate it if you can send a pull request to implement that 🥇

**Comment by tianhaoz95** [comment]
@all-contributors please add danielgomezrico for ideas

**Comment by tianhaoz95** [comment]
@danielgomezrico I added that option in #59 you can check https://tianhaoz.com/fastlane-plugin-flutter_version/#/?id=available-options for docs.
